package util.parkar.pakage;
import java.util.Scanner;

//GUESS THE NUMBER
//
//        aesthetic blob The fun and easy project "Guess the Number" is a short Java project that allows the
//        user to guess the number generated by the computer & involves the following steps:
//        1. The system generates a random number from a given range, say 1 to 100.
//        2. The user is prompted to enter their given number in a displayed dialogue box.
//        3. The computer then tells if the entered number matches the guesses number or it is
//        higher/lower than the generated number.
//        4. The game continues under the user guessing the number. You can also incorporate further details as:
//        Limiting the number of attempts.
//        Adding more rounds.
//        Displaying score.
//        Giving points based on the number of attempts.
//        aesthetic blob
public class NumberGame { //guess the number class
    public static void Guessnumber() //function for guess the number
    {
        Scanner in = new Scanner(System.in);
        int num = 1 + (int) (100 * Math.random());
        int chances = 7; //you have 7 chances to guess the number
        int rounds = 1; // Start from round 1
        int i, guess;
        int count = 0;
        System.out.println("Guess the number between 1 to 100. You have 7 chances, and you can play up to 3 rounds.");

        while (rounds <= 3) { // You have only 3 rounds
            System.out.println("Round: " + rounds);
            for (i = 0; i < chances; i++) {
                System.out.println("Guess the number:");
                guess = in.nextInt();
                if (num == guess) {
                    count++;
                    System.out.println("You won this round");
                    break; // Break out of the inner loop if the number is guessed
                } else if (num > guess) {
                    System.out.println("The number is greater than " + guess);
                } else {
                    System.out.println("The number is less than " + guess);
                }
            }

            if (i == chances) {
                System.out.println("You have used all 7 chances");
                System.out.println("The number is " + num);
            }

            rounds++;
        }

        System.out.println("Your score is: You won " + count + " rounds.");
        if(count == 0){
            System.out.println("you lose");
        }
        else if(count == 1){
            System.out.println("you lose");
           }
        else{
            System.out.println("you won");
        }
    }
    public static void main(String[] args) {

        Guessnumber();
    }

}
